#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: LOFFER
# Short bio or description (displayed in the header)
description: 一个可以fork的博客

#
# Flags below are optional
#

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/logo.png

# URL of your favicon
favicon: https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png


# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: 文章
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags

# Pagination
paginate: 8

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: 
  facebook:
  flickr:
  github: FromEndWorld/loffer
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: # <your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# Text under the icons in footer
footer-text: Copyright (c) 2019 来自中世界

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: #shortname

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: /LOFFER

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

excerpt_separator: ---
